- .gitignore
- packages/employer-client/src/Applications/ApplicationCreate.tsx
- packages/employer-client/src/Claims/ClaimCreate.tsx
- packages/employer-client/src/common/components/ListAside/ListAside.tsx
This was happening due to the application redirecting to the create screen and the user would remain there if they continue to refresh the page.
- Added a checker on ClaimCreate and ApplicationCreate to check for current total amount of applications returned, is the amount is not 0 then redirect to the main list page.
> TECH-466: Employer with no applications and claim forms can't get to landing page (removed sensitive)

- packages/employer-api/src/services/application.service.ts
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/common/components/ListAside/ListAside.tsx
In the employer client status sidebar, the number of 'Submitted' claims was sometimes incorrect.
This was because in the employer client, multiple internal statuses ('New', 'In Progress', and 'Completed') correspond to the 'Submitted' label in the sidebar. The previous code didn't handle this correctly.
This pull request addresses this issue by using two mappings to manage the status sidebar state:
{ status: label }
{ label: count }
Then we can obtain counts both by label and internal status value as required, ie:
counts[labels[status]]
or
counts[label]
> TECH-488: bug fix: display correct Submitted count in employer status sidebar

- packages/employer-client/src/Applications/ApplicationCreate.tsx
- packages/employer-client/src/Claims/ClaimCreate.tsx
Cause of issue: instead of returning a promise, the useGetList returns undefined on total before changing it to a number. This is satisfying the total !== 0 condition since undefined !== 0 = True.
- Added a type check for number then check if it's a 0, on first load and useGetList has not returned, where total is undefined, it would not redirect back to list until total has been changed to a number.
> TECH-502: Employer client: redirect from empty list loops on first load

- packages/admin-client/src/Form/ViewForm.tsx
Previously, the loading indicator wasn't appearing on form screens in the admin client. The logic for detecting the loading state had been implemented, but the code to render the loading indicator hadn't been added. This pull request adds those lines to resolve the issue.
> TECH-487: admin client: fix loading indicator

- packages/admin-client/src/common/components/CustomDatagrid/CustomDatagrid.tsx
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/common/components/CustomDatagrid/CustomDatagrid.tsx
Previously in the employer client, basic bceid users could open the Share dialog by selecting the checkbox on a list row, then clicking 'Share' in the form bulk actions menu. Only business bceid users should be able to access the Share dialog.
This pull request prevents basic bceid users from accessing the Share dialog by disabling list row checkboxes and the form bulk actions menu for basic bceid users.
> Only permit business bceid users to access Share dialog.

- packages/form-api/src/services/geocoder.service.ts
Cause:
- Form validation would only return the Full Address as 1 string, this will require us to split on CHEFS side.
- Utilizing the returned object properties from the Geocode API, FullAdress now is an object to be used in CHEFS to replace the user's address fields on validation.
> FullAddress is now an object with {address,city,province} for use in form validation

- packages/admin-client/src/App.tsx
- packages/admin-client/src/Applications/ApplicationList.tsx
- packages/admin-client/src/Claims/ClaimList.tsx
- packages/admin-client/src/Form/ViewForm.tsx
- packages/admin-client/src/common/components/CalculatorButtonField/CalculatorButtonField.tsx
This pull request fixes a bug where the embedded form and new-tab form would sometimes display in the wrong editing mode for the current status. The embedded and new-tab forms should now always display in the correct editing status corresponding to the current form status and user account type. Changes are as follows:
> TECH-543: always display form in correct editing mode

- packages/employer-api/src/services/application.service.ts
- packages/employer-api/src/services/claim.service.ts
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
- packages/employer-client/src/common/components/ListAside/ListAside.tsx
- packages/employer-client/src/common/components/SharedWithField/SharedWithField.tsx
- packages/employer-client/src/common/components/SharedWithField/SharedWithModal.tsx
This pull request improves the behaviour and usability of the Shared With column. It also attempts to fix a styling issue in the employer client where the list aside was misaligned with the list. Changes are as follows:
TECH-524:
TECH-525:
TECH-526:
> TECH-524, TECH-525, TECH-526: Fix Shared With column, list aside alignment

- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
- packages/employer-client/src/common/components/ListAside/ListAside.tsx
This pull request prevents guids from being passed through the URLs for list query endpoints. This was happening because the guid was part of the default list filter, and the list filter is passed to the API as a set of query parameters. We can remove the guid from the list filter and use the guid from the token instead, similar to other endpoints. Changes are as follows:
> TECH-548: Do not pass guids through list query endpoint URLs

- packages/employer-api/src/controllers/event.controller.ts
- packages/form-api/src/controllers/email.controller.ts
- packages/form-api/src/templates/notification.template.ts
Cause:
- email controller was reading applicationType and catchmentNo off of the data object.
- Wrapped post object to form API in data.
- Fixed spacing issues, typos on notification email title
Working current when I send a postman request to the endpoint with my own tokens.
> TECH-547: Employer client: internal server error after every form submission

- packages/employer-api/src/controllers/event.controller.ts
Cause:
- Claim notification sending will always return 500 due to the status checker but the status does not exist on returned object.
- Wrapped return 500 in a catch in event controller.
- Added typings to error and request in event controller.
> TECH-547-fix: Wrapping status 500 in a catch statement instead of checking for status on returned object.

- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
This pull request prevents the lists from containing the Shared With column for basic bceid users, since only business bceid users can share forms. The Shared With column and associated modal now render conditionally on the account type.
> TECH-552: restrict Shared With column to business bceid users

- packages/admin-api/src/controllers/application.controller.ts
- packages/admin-api/src/controllers/claim.controller.ts
- packages/admin-api/src/lib/transactions.ts
- packages/admin-api/src/services/application.service.ts
- packages/admin-api/src/services/claims.service.ts
- packages/admin-client/src/Applications/ApplicationList.tsx
- packages/admin-client/src/Claims/ClaimList.tsx
- packages/employer-api/src/controllers/application.controller.ts
- packages/employer-api/src/controllers/claim.controller.ts
- packages/employer-api/src/services/application.service.ts
- packages/employer-api/src/services/claim.service.ts
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimCreateSelectApplication.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
- packages/employer-client/src/common/components/CustomDatagrid/CustomDatagrid.tsx
This pull request allows the user to sort all lists by the default sort order by clicking the Submitted Date column header. It also prevents the SelectApplication list from ever containing checkboxes or a bulk actions menu, since the SelectApplication list is only used to select the associated application when a claim is created. Changes are as follows:
TECH-546:
TECH-554:
> TECH-546, TECH-554: Support custom sorting by date, remove checkboxes from SelectApplication list

- packages/admin-api/src/services/permission.service.ts
This pull request removes unsupported catchments (ie those not in range 1 - 45) from permissions query results, so they do not appear as options in the catchment dropdown.
> TECH-545: remove unsupported catchments from permissions query results

- packages/employer-api/src/config/CREATE_SCRIPTS.sql
- packages/employer-api/src/controllers/application.controller.ts
- packages/employer-api/src/controllers/claim.controller.ts
- packages/employer-api/src/routes/application.route.ts
- packages/employer-api/src/routes/claim.route.ts
- packages/employer-api/src/services/application.service.ts
- packages/employer-api/src/services/claim.service.ts
- packages/employer-client/src/App.tsx
- packages/employer-client/src/Applications/ApplicationCreate.tsx
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimCreateSelectApplication.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
- packages/employer-client/src/DataProvider/DataProvider.tsx
- packages/employer-client/src/Form/ViewForm.tsx
- packages/employer-client/src/common/components/CustomDatagrid/CustomDatagrid.tsx
> TECH-544: Implement improved sync design

- packages/employer-client/src/App.tsx
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
- packages/employer-client/src/UserProfileModal.tsx
- packages/employer-client/src/common/contexts/EmployerContext.tsx
This pull request resolves an issue where when the user logs in for the first time, the sync operation can occur before the employer record exists, causing the sync to fail with code 403. The sync operation is now delayed until the employer record is created or known to exist. This pull request also fixes an issue where on the list screen a delay was sometimes visible before the loading indicator activated. Changes are as follows:
> TECH-599: do not sync until employer record known to exist

- packages/employer-api/src/config/CREATE_SCRIPTS.sql
- packages/employer-api/src/controllers/application.controller.ts
- packages/employer-api/src/services/employer.service.ts
- packages/employer-client/src/UserProfileModal.tsx
This pull request removes the WorkBC Centre from the employer profile. This change prepares for the future change where the WorkBC Centre will always be determined automatically according to the employer address. Changes are as follows:
> TECH-582: remove WorkBC Centre from employer profile

- packages/employer-api/src/controllers/application.controller.ts
- packages/employer-api/src/controllers/event.controller.ts
- packages/employer-api/src/services/application.service.ts
- packages/employer-api/src/services/claim.service.ts
This pull request re-implements the employer data backfill functionality which was removed from the list queries as part of the new sync design. The employer data backfill now gets triggered in the event controller when the first application submission event is received for the user. This pull request also extends the event handling to trigger DB updates from all draft save or submit events, so DB syncs can occur without the user navigating back to the list after making form changes. Changes:
> TECH-610: move employer data backfill into event handler

- packages/admin-api/src/services/application.service.ts
- packages/admin-api/src/services/claims.service.ts
- packages/admin-client/src/Applications/ApplicationList.tsx
- packages/admin-client/src/Claims/ClaimList.tsx
- packages/employer-api/src/config/CREATE_SCRIPTS.sql
- packages/employer-api/src/services/application.service.ts
- packages/employer-api/src/services/claim.service.ts
- packages/employer-api/src/services/employer.service.ts
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimCreateSelectApplication.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
> TECH-553: fix timestamps

- packages/admin-api/src/controllers/application.controller.ts
This pull request fixes a bug where the employer email was not appearing in the application PDFs. The previous code was using the wrong field name to obtain the employer email from the CHEFS forms.
> TECH-600: fix bug: pass employer email into application PDFs

- packages/admin-client/src/Applications/ApplicationList.tsx
- packages/admin-client/src/Claims/ClaimList.tsx
- packages/employer-client/src/Applications/ApplicationList.tsx
- packages/employer-client/src/Claims/ClaimCreateSelectApplication.tsx
- packages/employer-client/src/Claims/ClaimList.tsx
This PR attempts to fix a bug where if the user changes the rows per page while the status filter is set to any value other than 'All', then returning to the 'All' filter has no effect, ie the 'All' filter permanently breaks.
After changing rows per page and returning to the 'All' filter, the filter values being passed into the List were correct, but the filter values in the resulting request to the API were wrong and still included the previous status filter. ie if the previous filter was 'Draft', then after returning to 'All' the filters sent in the request were:
label: All
status: Draft
It's unclear how the filters in the request were being set this way, it may be some internal functionality of React Admin.
The issue appears to resolve after setting the list filter default values to …
> TECH-588: fix bug where All filter breaks after changing perPage

- packages/employer-api/src/controllers/application.controller.ts
This PR fixes a bug where a null value could be passed from the employer profile into the workplace province in the form. Since the workplace province isn't editable in the form then the workplace address could not be validated. Changes:
> TECH-630: fix bug where workplace province unassignable after prefill

- packages/admin-api/src/controllers/application.controller.ts
- packages/employer-api/src/controllers/event.controller.ts
- workbc-wage-subsidy.code-workspace
This PR fixes a bug where backfill would not occur if the application submission notification failed.
This PR also adds the correct currency formatting for the hourly wage in application PDFs (TECH 640), and commits the new formatting changes to the code-workspace file applied by VSCode 18.5.
> TECH-621: permit backfill even if application notification fails

- packages/employer-api/src/controllers/application.controller.ts
- packages/employer-api/src/controllers/event.controller.ts
This PR fixes an issue where duplicate service provider claim forms could be created. It also fixes a minor issue where the workplace address validation result was not set to the correct default value when the workplace address was prefilled. Changes are as follows:
> TECH648: prevent duplicate service provider claim forms

- packages/employer-api/src/templates/notification.template.ts
- Updated email body in template to say "Wage Subsidy Claim Forms" for Claims and "Wage Subsidy Applications" for Applications.
- Updated email title in template to say "Wage Subsidy Claim Form" for Claim and "Wage Subsidy Application" for Application.
> Bug: Typos in Notification Email Template
